name: 🧋 Generate GitHub Metrics (簡約奶茶風)
on:
  schedule: [{cron: "0 0 * * *"}]
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: Sandyzhen
          template: classic
          plugin_languages: yes
          plugin_calendar: yes
          plugin_topics: yes
          plugin_activity: yes
          plugin_projects: yes
